# fly.toml app configuration file generated for backend-fastapi-sensors on 2024-08-22T11:59:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-fastapi-sensors'
primary_region = 'gru'

[build]
  dockerfile = './docker/Dockerfile'
  ignorefile = '.dockerignore'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
