"""Add name column to users table and made equipament_id as unique

Revision ID: 848a03e415e3
Revises: d082fb37354b
Create Date: 2024-08-16 17:09:51.641615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848a03e415e3'
down_revision: Union[str, None] = 'd082fb37354b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_equipment_equipment_id', table_name='equipment')
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=True)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.create_index('ix_equipment_equipment_id', 'equipment', ['equipment_id'], unique=False)
    # ### end Alembic commands ###
