"""Add user_company table and update relationships

Revision ID: 9c3f78c4e213
Revises: 848a03e415e3
Create Date: 2024-08-18 17:08:11.790446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3f78c4e213'
down_revision: Union[str, None] = '848a03e415e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_admin_user_id_fkey', 'companies', type_='foreignkey')
    op.drop_column('companies', 'admin_user_id')
    op.drop_index('ix_equipment_equipment_id', table_name='equipment')
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=False)
    op.create_unique_constraint('unique_company_equipment', 'equipment', ['company_id', 'equipment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_company_equipment', 'equipment', type_='unique')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.create_index('ix_equipment_equipment_id', 'equipment', ['equipment_id'], unique=True)
    op.add_column('companies', sa.Column('admin_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('companies_admin_user_id_fkey', 'companies', 'users', ['admin_user_id'], ['id'])
    # ### end Alembic commands ###
