"""Add admin_user_id to companies

Revision ID: d082fb37354b
Revises: 8856c469e8aa
Create Date: 2024-08-13 18:33:53.881955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd082fb37354b'
down_revision: Union[str, None] = '8856c469e8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('admin_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['admin_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'admin_user_id')
    # ### end Alembic commands ###
